
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7    # Python version 3.7
    - pandas
    - xarray        # N-d labeled array library
    - matplotlib    # 2D plotting library
    - mpl_toolkits
    - basemap
    - seaborn       # Statistical visualizations
